# Generated by Django 3.0.4 on 2020-04-16 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelCoefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField()),
                ('step', models.FloatField()),
                ('type', models.FloatField()),
                ('amount', models.FloatField()),
                ('oldBalanceDest', models.FloatField()),
                ('newBalanceDest', models.FloatField()),
                ('oldBalanceOrig', models.FloatField()),
                ('newBalanceOrig', models.FloatField()),
                ('errorBalanceDest', models.FloatField()),
                ('errorBalanceOrig', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('oldBalanceDest', models.FloatField()),
                ('newBalanceDest', models.FloatField()),
                ('oldBalanceOrig', models.FloatField()),
                ('newBalanceOrig', models.FloatField()),
                ('ownerBank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.Customer')),
            ],
        ),
    ]
