# Generated by Django 3.0.4 on 2020-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200416_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='errorBalanceDest',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='errorBalanceOrig',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(),
        ),
    ]
