# Generated by Django 3.0.4 on 2020-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200416_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='errorBalanceDest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='errorBalanceOrig',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='newBalanceDest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='newBalanceOrig',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='oldBalanceDest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='oldBalanceOrig',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
