# Generated by Django 3.0.4 on 2020-05-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200526_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelCoefs',
        ),
    ]
