# Generated by Django 3.0.4 on 2020-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_modelcoefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='prediction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trained',
            field=models.BooleanField(default=False),
        ),
    ]
